# Generated by Django 4.1.1 on 2022-10-17 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ejercicios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ejercicio',
            name='PrimerNumero',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='ejercicio',
            name='SegundoNumero',
            field=models.IntegerField(default=2),
        ),
    ]
